name: 'Build Muszka Corne-ish Zen'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "corneish_zen_v2_left","corneish_zen_v2_right"
      ]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      clipboard: '["Mac"]'
      layers: '["flip"]'
      kconfig: '["CONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2"]'
